### PR TITLE
Avoid using file rename

### LINKED ISSUE #1: Rename fails with "invalid cross-device link"
According to [stackoverflow](https://stackoverflow.com/a/24210631/503798) we can fallback to copy and delete when this occurs.

    gvm: error: rename /tmp/go1.8.3.linux.amd64651688074/go /var/lib/jenkins/.gvm/versions/go1.8.3.linux.amd64: invalid cross-device link

### PR DESCRIPTION
**Pull request by andrewkroh**
Changed code to extract the Go distribution directly into HOME instead of extracting to a temp dir and then moving to HOME. On some systems using `os.Rename` (move) across devices resulted in EXDEV (invalid cross-device link).

Fixes #1

### CODE REVIEW

File: golang/golang.go [hunk 1]
```diff
@@ -36,7 +37,7 @@ func SetupGolang(version string) (string, error) {
 	}
 
 	if !isGoInstalled(goDir) {
-		tmp, err := ioutil.TempDir("", fmt.Sprintf("go%s.%s.%s", version, runtime.GOOS, runtime.GOARCH))
+		tmp, err := ioutil.TempDir("", filepath.Base(goDir))
```
Comment (ruflin) [inline golang/golang.go]: I remember @jalvz mentioned today that TempDir has some issues on Windows?

Comment (andrewkroh) [inline golang/golang.go]: Like what? Other than the location varying a bit based on the environment (see [`GetTempPath`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992(v=vs.85).aspx)) I haven't noticed any issues.
